services:
  - type: static site
    name: elscooter
    buildCommand: npm install && ./node_modules/.bin/react-scripts build
    publishDir: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
