services:
  - type: static site
    name: el-scooter-control
    buildCommand: npm install && npm run build
    publishDir: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html